# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 600)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setStyleSheet(u"alternate-background-color: rgb(136, 136, 136);")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_5 = QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.id_lineEdit = QLineEdit(self.groupBox)
        self.id_lineEdit.setObjectName(u"id_lineEdit")
        self.id_lineEdit.setGeometry(QRect(50, 20, 81, 20))
        self.velocidad_spinBox = QSpinBox(self.groupBox)
        self.velocidad_spinBox.setObjectName(u"velocidad_spinBox")
        self.velocidad_spinBox.setGeometry(QRect(70, 220, 39, 20))
        self.velocidad_spinBox.setMaximum(100)
        self.mostrar_pushButton = QPushButton(self.groupBox)
        self.mostrar_pushButton.setObjectName(u"mostrar_pushButton")
        self.mostrar_pushButton.setGeometry(QRect(730, 450, 91, 31))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 220, 45, 16))
        self.agregar_inicio_pushButton = QPushButton(self.groupBox)
        self.agregar_inicio_pushButton.setObjectName(u"agregar_inicio_pushButton")
        self.agregar_inicio_pushButton.setGeometry(QRect(200, 450, 111, 31))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 20, 16, 16))
        self.agregar_final_pushButton = QPushButton(self.groupBox)
        self.agregar_final_pushButton.setObjectName(u"agregar_final_pushButton")
        self.agregar_final_pushButton.setGeometry(QRect(460, 450, 101, 31))
        self.salida = QPlainTextEdit(self.groupBox)
        self.salida.setObjectName(u"salida")
        self.salida.setGeometry(QRect(160, 10, 681, 431))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 260, 101, 111))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 19, 16))
        self.red_spinBox = QSpinBox(self.groupBox_2)
        self.red_spinBox.setObjectName(u"red_spinBox")
        self.red_spinBox.setGeometry(QRect(50, 20, 39, 20))
        self.red_spinBox.setMaximum(255)
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 29, 16))
        self.green_spinBox = QSpinBox(self.groupBox_2)
        self.green_spinBox.setObjectName(u"green_spinBox")
        self.green_spinBox.setGeometry(QRect(50, 50, 39, 20))
        self.green_spinBox.setMaximum(255)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 20, 16))
        self.blue_spinBox = QSpinBox(self.groupBox_2)
        self.blue_spinBox.setObjectName(u"blue_spinBox")
        self.blue_spinBox.setGeometry(QRect(50, 80, 39, 20))
        self.blue_spinBox.setMaximum(255)
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 50, 121, 81))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 41, 16))
        self.origenx_spinBox = QSpinBox(self.groupBox_3)
        self.origenx_spinBox.setObjectName(u"origenx_spinBox")
        self.origenx_spinBox.setGeometry(QRect(60, 20, 39, 20))
        self.origenx_spinBox.setStyleSheet(u"border-left-color: rgb(47, 128, 237);\n"
"gridline-color: rgb(176, 196, 237);\n"
"selection-background-color: rgb(85, 170, 255);")
        self.origenx_spinBox.setMaximum(500)
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 41, 16))
        self.origenY_spinBox = QSpinBox(self.groupBox_3)
        self.origenY_spinBox.setObjectName(u"origenY_spinBox")
        self.origenY_spinBox.setGeometry(QRect(60, 50, 39, 20))
        self.origenY_spinBox.setMaximum(500)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 130, 120, 80))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 45, 16))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 45, 16))
        self.destinox_spinBox = QSpinBox(self.groupBox_4)
        self.destinox_spinBox.setObjectName(u"destinox_spinBox")
        self.destinox_spinBox.setGeometry(QRect(60, 20, 39, 20))
        self.destinox_spinBox.setMaximum(500)
        self.destinoy_spinBox = QSpinBox(self.groupBox_4)
        self.destinoy_spinBox.setObjectName(u"destinoy_spinBox")
        self.destinoy_spinBox.setGeometry(QRect(60, 50, 39, 20))
        self.destinoy_spinBox.setMaximum(500)
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 390, 91, 111))
        self.id_pushButton = QPushButton(self.groupBox_5)
        self.id_pushButton.setObjectName(u"id_pushButton")
        self.id_pushButton.setGeometry(QRect(0, 20, 75, 23))
        self.distancia_pushButton = QPushButton(self.groupBox_5)
        self.distancia_pushButton.setObjectName(u"distancia_pushButton")
        self.distancia_pushButton.setGeometry(QRect(0, 50, 75, 23))
        self.velocidad_pushButton = QPushButton(self.groupBox_5)
        self.velocidad_pushButton.setObjectName(u"velocidad_pushButton")
        self.velocidad_pushButton.setGeometry(QRect(0, 80, 75, 23))

        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_2 = QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabla = QTableWidget(self.tab_2)
        self.tabla.setObjectName(u"tabla")

        self.gridLayout_2.addWidget(self.tabla, 0, 0, 1, 3)

        self.buscar_lineEdit = QLineEdit(self.tab_2)
        self.buscar_lineEdit.setObjectName(u"buscar_lineEdit")
        self.buscar_lineEdit.setDragEnabled(True)

        self.gridLayout_2.addWidget(self.buscar_lineEdit, 1, 0, 1, 1)

        self.buscar_pushButton = QPushButton(self.tab_2)
        self.buscar_pushButton.setObjectName(u"buscar_pushButton")

        self.gridLayout_2.addWidget(self.buscar_pushButton, 1, 1, 1, 1)

        self.mostrar_tabla_pushButton = QPushButton(self.tab_2)
        self.mostrar_tabla_pushButton.setObjectName(u"mostrar_tabla_pushButton")

        self.gridLayout_2.addWidget(self.mostrar_tabla_pushButton, 1, 2, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout_3 = QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.dibujar = QPushButton(self.tab_3)
        self.dibujar.setObjectName(u"dibujar")

        self.gridLayout_3.addWidget(self.dibujar, 0, 0, 1, 1)

        self.graphicsView = QGraphicsView(self.tab_3)
        self.graphicsView.setObjectName(u"graphicsView")

        self.gridLayout_3.addWidget(self.graphicsView, 0, 1, 5, 1)

        self.get_particulas_pushButton = QPushButton(self.tab_3)
        self.get_particulas_pushButton.setObjectName(u"get_particulas_pushButton")

        self.gridLayout_3.addWidget(self.get_particulas_pushButton, 1, 0, 1, 1)

        self.particulas_cercanas_pushButton = QPushButton(self.tab_3)
        self.particulas_cercanas_pushButton.setObjectName(u"particulas_cercanas_pushButton")

        self.gridLayout_3.addWidget(self.particulas_cercanas_pushButton, 2, 0, 1, 1)

        self.limpiar = QPushButton(self.tab_3)
        self.limpiar.setObjectName(u"limpiar")

        self.gridLayout_3.addWidget(self.limpiar, 3, 0, 1, 1)

        self.groupBox_6 = QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.Djikstra_pushButton = QPushButton(self.groupBox_6)
        self.Djikstra_pushButton.setObjectName(u"Djikstra_pushButton")
        self.Djikstra_pushButton.setGeometry(QRect(10, 20, 101, 23))
        self.Prim_pushButton = QPushButton(self.groupBox_6)
        self.Prim_pushButton.setObjectName(u"Prim_pushButton")
        self.Prim_pushButton.setGeometry(QRect(10, 50, 101, 23))
        self.Kruskal_pushButton = QPushButton(self.groupBox_6)
        self.Kruskal_pushButton.setObjectName(u"Kruskal_pushButton")
        self.Kruskal_pushButton.setGeometry(QRect(10, 80, 101, 23))
        self.algoritmos_plainTextEdit = QPlainTextEdit(self.groupBox_6)
        self.algoritmos_plainTextEdit.setObjectName(u"algoritmos_plainTextEdit")
        self.algoritmos_plainTextEdit.setGeometry(QRect(10, 130, 111, 241))

        self.gridLayout_3.addWidget(self.groupBox_6, 4, 0, 1, 1)

        self.tabWidget.addTab(self.tab_3, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 901, 21))
        self.menuParticulas = QMenu(self.menubar)
        self.menuParticulas.setObjectName(u"menuParticulas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuParticulas.menuAction())
        self.menuParticulas.addAction(self.actionAbrir)
        self.menuParticulas.addAction(self.actionGuardar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Particulas", None))
        self.mostrar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.agregar_inicio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agrega Inicio", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.agregar_final_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agrega Final", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Colores RGB", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Origenes", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Origen X", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Origen Y", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Destinos", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Destino X", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Destino Y", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Ordenar por:", None))
        self.id_pushButton.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.distancia_pushButton.setText(QCoreApplication.translate("MainWindow", u"Distancia", None))
        self.velocidad_pushButton.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.buscar_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID de la particula", None))
        self.buscar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.mostrar_tabla_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tabla", None))
        self.dibujar.setText(QCoreApplication.translate("MainWindow", u"Dibujar", None))
        self.get_particulas_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar solo (X, Y)", None))
        self.particulas_cercanas_pushButton.setText(QCoreApplication.translate("MainWindow", u"Particulas mas cercanas", None))
        self.limpiar.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Algoritmos", None))
        self.Djikstra_pushButton.setText(QCoreApplication.translate("MainWindow", u"Djikstra", None))
        self.Prim_pushButton.setText(QCoreApplication.translate("MainWindow", u"Prim", None))
        self.Kruskal_pushButton.setText(QCoreApplication.translate("MainWindow", u"Kruskal", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Grafico", None))
        self.menuParticulas.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

